### ISSUE TITLE
Add integration tests to to CI pipeline (Playwright)

### ISSUE THREAD

**Issue by marco-souza** [podcodar/webapp#158]
To avoid publishing a broken version of our app, we need to run integration tests before deploying to production.

I suggest implementing integration tests to validate our main workflows. This also simplifies the migration work for the next latest version.

**Tasks**:

- [x] setup playwright for our site
  - [x] run it locally
- [x] setup GitHub Actions
- [x] Implement integration tests

**References**:

- https://playwright.dev/docs/ci-intro
