### ISSUE TITLE
[story] Migrate to TailwindCSS and Daisy UI

### ISSUE THREAD

**Issue by marco-souza** [podcodar/webapp#164]
## Tasks

- [x] Tailwindcss - https://tailwindcss.com/
  - [x] #172
- [x] Daisy UI - https://daisyui.com/
  - [x] #174
  - [x] #181
- [ ] Migrate Components
  - [ ] Colors
      - [x] #183
      - [x] #184
      - [ ] #225
  - [x] Multipage
    - [x] #176
    - [x] #214
    - [x] #192
    - [x] #218
  - [x] Home Page - https://www.podcodar.org/
    - [x] #197
    - [x] #200
    - [x] #204
    - [x] #203
    - [x] #193
      - [x] #206
    - [x] #208
    - [x] #187
      - [x] #213
  - [x] Team Page - https://www.podcodar.org/team
    - [x] #215
    - [x] #219
  - [x] Not Found Page - https://www.podcodar.org/404
    - [x] #217
- [ ] Remove `Chakra` dependency
  - [x] #226
  - [x] #223

**Comment by Joel-leal** [comment]
Wouldn't this task be broken down into several tasks?

**Comment by Diegiwg** [comment]
Yes, each component to be migrated will be done in its own task (issue and PR).

And if the person responsible for the migration feels the need to break it down into more tasks, they are free to do so.
