### ISSUE TITLE
[story] Server-side Localized pages - |🇧🇷 |🇺🇸

### ISSUE THREAD

**Issue by marco-souza** [podcodar/webapp#199]
## Description

Our web app uses client-side translations in React. This works fine, but it requires all components and pages that use any text to be client-side rendered, killing next.js server-side features.

With that done, we expect to:
- [ ] improve page load performance
- [ ] Improve server caching
- [ ] use server-side features
- [ ] No sub-

**DRIs**: @marco-souza @frattezi 

### Task Breakdown

- [x] #202
- [ ] Implement Localized URLs `/pt-br/something`, default is `en` -> `/` 
- [ ] Use `Accept-Language` header info to translate page, default `en`
- [ ] Use cookie `prefered_language` to translate the page

**Comment by marco-souza** [comment]
For now, having the translation feature on the client side is beneficial, but we needed to localize the translation to avoid having it available as a react hook.

Closing this story for now
