### ISSUE TITLE
Criar um webapp Next + Chakra com multiplas paginas

### ISSUE THREAD

**Issue by marco-souza** [podcodar/webapp#59]
# Description

Com time de desenvolvimento do webapp da PodCodar, precisamos passar por alguns conceitos básicos das ferramentas que usamos. Para isso vamos fazer uma tarefa de descoberta das ferramentas

## Critérios de Aceite

- criar uma aplicação utilizando Next.JS e Chakra (links nas Meeting Notes)
- aplicação deve ter multiplas páginas
- subir aplicação no seu github pessoal

## Sub-tasks
- [ ] pesquisar sobre:
  - [x] Yarn (alternativa ao npm que  iremos usar)
  - [x] Next.js (framework de React)
  - [x] Chrakra (css para React)
- [x] instalar `yarn` no seu computador pessoal
- [x] criar um project next com `yarn create next-app`
- [x] criar uma aplicação multi page com as ferramentas estudadas

# Links

- [Meeting Notes][1]

[1]: https://podcodar.notion.site/Sprint-Planing-1-5040a28bba2743d4970b8ceea24cc38f
