### ISSUE TITLE
Criar um webapp multi-page com Next.js + Chakra.

### ISSUE THREAD

**Issue by marco-souza** [podcodar/webapp#61]
# Description

Com time de desenvolvimento do webapp da PodCodar, precisamos passar por alguns conceitos básicos das ferramentas que usamos. Para isso vamos fazer uma tarefa de descoberta das ferramentas

## Critérios de Aceite

- criar uma aplicação utilizando Next.JS e Chakra (links nas Meeting Notes)
- aplicação deve ter multiplas páginas
- subir aplicação no seu github pessoal

## Sub-tasks
- [ ] pesquisar sobre:
  - [ ] Yarn (alternativa ao npm que  iremos usar)
  - [ ] Next.js (framework de React)
  - [ ] Chrakra (css para React)
- [ ] instalar `yarn` no seu computador pessoal
- [ ] criar um project next com `yarn create next-app`
- [ ] criar uma aplicação multi page com as ferramentas estudadas

# Links

- [Meeting Notes][1]

[1]: https://podcodar.notion.site/Sprint-Planing-1-5040a28bba2743d4970b8ceea24cc38f

**Comment by marco-souza** [comment]
@wevertonvetim depois lembra de fechar esse card
